# -*- coding: utf-8 -*-
"""AulaDeteccaoFruadesTransacoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEakkDpktdeo7m8x8tEKWHzSPpPphmMa

# Detecção de Fraudes em Transações
"""

import pandas as pd
url = "http://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv"
df = pd.read_csv(url)
df.head()

"""# Problema de classificação desbalanceada

Fraudes são raras → modelo pode ignorar a classe 1


"""

df["Class"].value_counts(normalize = True)

"""# Feature Engineering
Criamos variáveis que ajudam o modelo
"""

import numpy as np
df["Amount_log"] = np.log1p(df["Amount"])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df["Amount_scaled"] = scaler.fit_transform(df[["Amount"]])

from sklearn.model_selection import train_test_split
x = df.drop("Class", axis=1)
y = df["Class"]

x_train, x_test, y_train, y_test = train_test_split(
    x, y, stratify=y, test_size=0.3, random_state=42
)

"""# Logistic Regression"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

"""Accuracy pode alta mesmo sem detectar fraudes
Por isso usamos:


*   Recall (mais importante)
*   Precision
*   F1-score


"""

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
y_probs = model.predict_proba(x_test)[:,1]
fpr, tpr, _ = roc_curve(y_test, y_probs)
plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()
print("AUC: ", roc_auc_score(y_test, y_probs))

from sklearn.metrics import precision_recall_curve
precision, recall, _ = precision_recall_curve(y_test, y_probs)
plt.plot(recall, precision)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

"""# Balanceamento de Dados"""

# Undersampling
fraudes = df[df["Class"] == 1]
normais = df[df["Class"] == 0].sample(len(fraudes),random_state=42)
df_under = pd.concat([fraudes, normais])

# Oversampling
from imblearn.over_sampling import SMOTE
smote = SMOTE()
x_res, y_res = smote.fit_resample(x, y)

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators = 50,
    max_depth = 10,
    class_weight = "balanced",
    n_jobs = -1,
    random_state=42
)
rf.fit(x_train, y_train)
y_pred_rf = rf.predict(x_test)
print(classification_report(y_test, y_pred_rf))

from sklearn.pipeline import Pipeline
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter = 1000))
])
pipeline.fit(x_train, y_train)
y_pred = pipeline.predict(x_test)

threshold = 0.3
y_pred_custom = (y_probs > threshold).astype(int)
print(classification_report(y_test, y_pred_custom))

"""# Modelo Avaçando - XGBoost
XGBoost é um dos algoritmos em competições e mercado.
Ele é mais poderoso que o Random Forest para muitos problemas.
"""

from xgboost import XGBClassifier
xgb = XGBClassifier(
    scale_pos_weight=10,
    use_label_encoder = False,
    eval_metric = "logloss"
)
xgb.fit(x_train, y_train)
y_pred_xgb = xgb.predict(x_test)

print(classification_report(y_test, y_pred_xgb))

"""# Importância das Variáveis
Ajuda a entender quais variáveis influenciam mais o modelo.
"""

importancias = xgb.feature_importances_
plt.bar(range(len(importancias)),importancias)
plt.title("Importância das Variáveis")
plt.show()

"""# Ajuste de Hiperparâmetros
Testamos várias combinações para melhorar o modelo.
"""

from sklearn.model_selection import GridSearchCV
param_grid = {
    "max_depth": [3, 5],
    "n_estimators": [50, 100]
}
grid = GridSearchCV(
    XGBClassifier(eval_metric = "logloss"),
    param_grid,
    scoring = "recall",
    cv = 3
)
grid.fit(x_train, y_train)
print("Melhor Modelo: ", grid.best_params_)

"""# Explicabilidade (SHAP)
SHAP mostra como cada variável influencia a decisão do modelo.
"""

import shap
explainer = shap.Explainer(xgb)
shap_values = explainer(x_test[:100])
shap.plots.bar(shap_values)